[
  verbose: true,
  private: false,
  skip: false,
  router: "AlchemistdropsWeb.Router",
  exit: "high",
  format: "txt",
  out: "",
  threshold: "medium",
  ignore: ["Config.CSP"],
  ignore_files: []
]