[
  Alchemistdrops.Application,
  AlchemistdropsWeb.Layouts,
  Alchemistdrops.Repo,
  AlchemistdropsWeb.Telemetry,
  Mix.Tasks.Coverage.Index,
  Alchemistdrops.AccountsFixtures,
  AlchemistdropsWeb.ErrorHTML,
  Alchemistdrops.CoursesFixtures,
  Alchemistdrops.EnrollmentsFixtures,
  Alchemistdrops.PaymentsFixtures
]
