defmodule Alchemistdrops.PostsTest do
  use Alchemistdrops.DataCase

  alias Alchemistdrops.Posts

  describe "posts" do
    alias Alchemistdrops.Posts.{Category, Post, Tag}

    import Alchemistdrops.PostsFixtures

    @invalid_attrs %{title: nil, body: nil, background: nil, views: nil}

    test "list_posts/0 returns all posts" do
      post = post_fixture()
      assert Posts.list_posts() == [post]
    end

    test "get_post!/1 returns the post with given id" do
      post = post_fixture()
      assert Posts.get_post!(post.id) == post
    end

    test "get_post_by_slug!/1 returns the post with given slug" do
      post = post_fixture(%{title: "Slug Lookup Post"})

      assert Posts.get_post_by_slug!("slug-lookup-post").id == post.id
    end

    test "create_post/1 with valid data creates a post" do
      valid_attrs = %{
        title: "some title",
        body: "some body",
        background: "some background",
        views: 42
      }

      assert {:ok, %Post{} = post} = Posts.create_post(valid_attrs)
      assert post.title == "some title"
      assert post.body == "some body"
      assert post.background == "some background"
      assert post.views == 42
      assert post.slug == "some-title"
    end

    test "create_post/1 returns a changeset error when the generated slug already exists" do
      first_post = post_fixture(%{title: "Duplicate Title"})

      assert {:error, %Ecto.Changeset{} = changeset} =
               Posts.create_post(%{
                 title: "Duplicate Title",
                 body: "some body",
                 background: "some background",
                 views: 42
               })

      assert first_post.slug == "duplicate-title"
      assert %{slug: ["has already been taken"]} = errors_on(changeset)
    end

    test "create_post/1 with invalid data returns error changeset" do
      assert {:error, %Ecto.Changeset{}} = Posts.create_post(@invalid_attrs)
    end

    test "post changeset generates a slug from the title" do
      changeset =
        Post.changeset(%Post{}, %{
          title: "Generated By Changeset",
          body: "some body",
          views: 42
        })

      assert Ecto.Changeset.get_change(changeset, :slug) == "generated-by-changeset"
    end

    test "draft_changeset/2 allows publication-only fields to remain empty" do
      changeset = Post.draft_changeset(%Post{}, %{title: "Work in progress"})

      assert changeset.valid?
      assert Ecto.Changeset.get_field(changeset, :status) == :draft
      assert Ecto.Changeset.get_field(changeset, :slug) == "work-in-progress"
    end

    test "publish_changeset/2 requires the editorial publication fields" do
      changeset = Post.publish_changeset(%Post{}, %{title: "Incomplete article"})

      refute changeset.valid?

      assert %{
               body: ["can't be blank"],
               category_id: ["can't be blank"],
               summary: ["can't be blank"]
             } = errors_on(changeset)
    end

    test "draft_changeset/2 requires alternative text when a cover image is present" do
      changeset =
        Post.draft_changeset(%Post{}, %{
          title: "Article with cover",
          cover_image_url: "https://example.com/cover.jpg"
        })

      refute changeset.valid?

      assert %{cover_image_alt: ["can't be blank when a cover image is present"]} =
               errors_on(changeset)
    end

    test "publish_changeset/2 accepts string-keyed form parameters" do
      changeset =
        Post.publish_changeset(%Post{}, %{
          "title" => "Publish from form",
          "body" => "Complete body",
          "summary" => "Complete summary",
          "category_id" => Ecto.UUID.generate()
        })

      assert changeset.valid?
      assert Ecto.Changeset.get_field(changeset, :status) == :published
    end

    test "draft_changeset/2 rejects non-HTTPS cover image URLs" do
      changeset =
        Post.draft_changeset(%Post{}, %{
          title: "Unsafe cover",
          cover_image_url: "http://example.com/cover.jpg",
          cover_image_alt: "Cover"
        })

      refute changeset.valid?
      assert %{cover_image_url: ["must be an absolute HTTPS URL"]} = errors_on(changeset)
    end

    test "category changeset trims its name and generates a stable slug" do
      changeset = Category.changeset(%Category{}, %{name: "  Phoenix LiveView  "})

      assert changeset.valid?
      assert Ecto.Changeset.get_field(changeset, :name) == "Phoenix LiveView"
      assert Ecto.Changeset.get_field(changeset, :slug) == "phoenix-liveview"
    end

    test "tag changeset trims its name and generates a stable slug" do
      changeset = Tag.changeset(%Tag{}, %{name: "  OTP & BEAM  "})

      assert changeset.valid?
      assert Ecto.Changeset.get_field(changeset, :name) == "OTP & BEAM"
      assert Ecto.Changeset.get_field(changeset, :slug) == "otp-beam"
    end

    test "update_post/2 with valid data updates the post" do
      post = post_fixture()

      update_attrs = %{
        title: "some updated title",
        body: "some updated body",
        background: "some updated background",
        views: 43
      }

      assert {:ok, %Post{} = post} = Posts.update_post(post, update_attrs)
      assert post.title == "some updated title"
      assert post.body == "some updated body"
      assert post.background == "some updated background"
      assert post.views == 43
      assert post.slug == "some-title"
    end

    test "update_post/2 keeps the existing slug when title changes" do
      post = post_fixture(%{title: "Original Title"})

      assert {:ok, %Post{} = post} = Posts.update_post(post, %{title: "Updated Title"})

      assert post.title == "Updated Title"
      assert post.slug == "original-title"
    end

    test "update_post/2 with invalid data returns error changeset" do
      post = post_fixture()
      assert {:error, %Ecto.Changeset{}} = Posts.update_post(post, @invalid_attrs)
      assert post == Posts.get_post!(post.id)
    end

    test "delete_post/1 deletes the post" do
      post = post_fixture()
      assert {:ok, %Post{}} = Posts.delete_post(post)
      assert_raise Ecto.NoResultsError, fn -> Posts.get_post!(post.id) end
    end

    test "change_post/1 returns a post changeset" do
      post = post_fixture()
      assert %Ecto.Changeset{} = Posts.change_post(post)
    end
  end
end
