defmodule Alchemistdrops.PostsTest do
  use Alchemistdrops.DataCase

  alias Alchemistdrops.Posts

  describe "posts" do
    alias Alchemistdrops.Posts.{Category, Post, Tag}

    import Alchemistdrops.PostsFixtures

    @invalid_attrs %{title: nil, body: nil, background: nil, views: nil}

    test "list_posts/0 returns all posts" do
      post = post_fixture()
      assert Posts.list_posts() == [post]
    end

    test "get_post!/1 returns the post with given id" do
      post = post_fixture()
      assert Posts.get_post!(post.id) == post
    end

    test "get_post_by_slug!/1 returns the post with given slug" do
      post = post_fixture(%{title: "Slug Lookup Post"})

      assert Posts.get_post_by_slug!("slug-lookup-post").id == post.id
    end

    test "create_post/1 with valid data creates a post" do
      valid_attrs = %{
        title: "some title",
        body: "some body",
        background: "some background",
        views: 42
      }

      assert {:ok, %Post{} = post} = Posts.create_post(valid_attrs)
      assert post.title == "some title"
      assert post.body == "some body"
      assert post.background == "some background"
      assert post.views == 42
      assert post.slug == "some-title"
    end

    test "create_post/1 returns a changeset error when the generated slug already exists" do
      first_post = post_fixture(%{title: "Duplicate Title"})

      assert {:error, %Ecto.Changeset{} = changeset} =
               Posts.create_post(%{
                 title: "Duplicate Title",
                 body: "some body",
                 background: "some background",
                 views: 42
               })

      assert first_post.slug == "duplicate-title"
      assert %{slug: ["has already been taken"]} = errors_on(changeset)
    end

    test "create_post/1 with invalid data returns error changeset" do
      assert {:error, %Ecto.Changeset{}} = Posts.create_post(@invalid_attrs)
    end

    test "post changeset generates a slug from the title" do
      changeset =
        Post.changeset(%Post{}, %{
          title: "Generated By Changeset",
          body: "some body",
          views: 42
        })

      assert Ecto.Changeset.get_change(changeset, :slug) == "generated-by-changeset"
    end

    test "draft_changeset/2 allows publication-only fields to remain empty" do
      changeset = Post.draft_changeset(%Post{}, %{title: "Work in progress"})

      assert changeset.valid?
      assert Ecto.Changeset.get_field(changeset, :status) == :draft
      assert Ecto.Changeset.get_field(changeset, :slug) == "work-in-progress"
    end

    test "publish_changeset/2 requires the editorial publication fields" do
      changeset = Post.publish_changeset(%Post{}, %{title: "Incomplete article"})

      refute changeset.valid?

      assert %{
               body: ["can't be blank"],
               category_id: ["can't be blank"],
               summary: ["can't be blank"]
             } = errors_on(changeset)
    end

    test "draft_changeset/2 requires alternative text when a cover image is present" do
      changeset =
        Post.draft_changeset(%Post{}, %{
          title: "Article with cover",
          cover_image_url: "https://example.com/cover.jpg"
        })

      refute changeset.valid?

      assert %{cover_image_alt: ["can't be blank when a cover image is present"]} =
               errors_on(changeset)
    end

    test "publish_changeset/2 accepts string-keyed form parameters" do
      changeset =
        Post.publish_changeset(%Post{}, %{
          "title" => "Publish from form",
          "body" => "Complete body",
          "summary" => "Complete summary",
          "category_id" => Ecto.UUID.generate()
        })

      assert changeset.valid?
      assert Ecto.Changeset.get_field(changeset, :status) == :published
    end

    test "draft_changeset/2 rejects non-HTTPS cover image URLs" do
      changeset =
        Post.draft_changeset(%Post{}, %{
          title: "Unsafe cover",
          cover_image_url: "http://example.com/cover.jpg",
          cover_image_alt: "Cover"
        })

      refute changeset.valid?
      assert %{cover_image_url: ["must be an absolute HTTPS URL"]} = errors_on(changeset)
    end

    test "category changeset trims its name and generates a stable slug" do
      changeset = Category.changeset(%Category{}, %{name: "  Phoenix LiveView  "})

      assert changeset.valid?
      assert Ecto.Changeset.get_field(changeset, :name) == "Phoenix LiveView"
      assert Ecto.Changeset.get_field(changeset, :slug) == "phoenix-liveview"
    end

    test "tag changeset trims its name and generates a stable slug" do
      changeset = Tag.changeset(%Tag{}, %{name: "  OTP & BEAM  "})

      assert changeset.valid?
      assert Ecto.Changeset.get_field(changeset, :name) == "OTP & BEAM"
      assert Ecto.Changeset.get_field(changeset, :slug) == "otp-beam"
    end

    test "update_post/2 with valid data updates the post" do
      post = post_fixture()

      update_attrs = %{
        title: "some updated title",
        body: "some updated body",
        background: "some updated background",
        views: 43
      }

      assert {:ok, %Post{} = post} = Posts.update_post(post, update_attrs)
      assert post.title == "some updated title"
      assert post.body == "some updated body"
      assert post.background == "some updated background"
      assert post.views == 43
      assert post.slug == "some-title"
    end

    test "update_post/2 keeps the existing slug when title changes" do
      post = post_fixture(%{title: "Original Title"})

      assert {:ok, %Post{} = post} = Posts.update_post(post, %{title: "Updated Title"})

      assert post.title == "Updated Title"
      assert post.slug == "original-title"
    end

    test "update_post/2 with invalid data returns error changeset" do
      post = post_fixture()
      assert {:error, %Ecto.Changeset{}} = Posts.update_post(post, @invalid_attrs)
      assert post == Posts.get_post!(post.id)
    end

    test "delete_post/1 deletes the post" do
      post = post_fixture()
      assert {:ok, %Post{}} = Posts.delete_post(post)
      assert_raise Ecto.NoResultsError, fn -> Posts.get_post!(post.id) end
    end

    test "change_post/1 returns a post changeset" do
      post = post_fixture()
      assert %Ecto.Changeset{} = Posts.change_post(post)
    end

    test "public queries exclude drafts and preload editorial associations" do
      published = post_fixture(%{title: "Visible article"})
      draft = draft_post_fixture(%{title: "Private draft"})

      assert [listed] = Posts.list_published_posts()
      assert listed.id == published.id
      assert Ecto.assoc_loaded?(listed.category)
      assert Ecto.assoc_loaded?(listed.tags)
      refute Enum.any?(Posts.list_published_posts(), &(&1.id == draft.id))

      assert Posts.get_published_post_by_slug!(published.slug).id == published.id

      assert_raise Ecto.NoResultsError, fn ->
        Posts.get_published_post_by_slug!(draft.slug)
      end
    end

    test "publish_post/1 stamps the first publication and unpublish_post/1 hides the article" do
      category = category_fixture()

      draft =
        draft_post_fixture(%{
          title: "Ready article",
          body: "Complete body",
          summary: "Complete summary",
          category_id: category.id
        })

      assert {:ok, published} = Posts.publish_post(draft)
      assert published.status == :published
      assert published.published_at
      first_published_at = published.published_at

      assert {:ok, draft_again} = Posts.unpublish_post(published)
      assert draft_again.status == :draft

      assert {:ok, republished} = Posts.publish_post(draft_again)
      assert republished.published_at == first_published_at
    end

    test "create_post/1 reuses category and tag names case-insensitively" do
      attrs = %{
        title: "Taxonomy article",
        category_name: "Elixir",
        tag_names: "OTP, beam, OTP"
      }

      assert {:ok, first_post} = Posts.create_post(attrs)

      assert {:ok, second_post} =
               Posts.create_post(%{
                 title: "Another taxonomy article",
                 category_name: "elixir",
                 tag_names: "otp, BEAM"
               })

      first_post = Repo.preload(first_post, [:category, :tags])
      second_post = Repo.preload(second_post, [:category, :tags])

      assert first_post.category.id == second_post.category.id
      assert Enum.sort(Enum.map(first_post.tags, & &1.slug)) == ["beam", "otp"]

      assert Enum.sort(Enum.map(second_post.tags, & &1.id)) ==
               Enum.sort(Enum.map(first_post.tags, & &1.id))
    end

    test "create_post/1 rejects more than five unique tags" do
      assert {:error, changeset} =
               Posts.create_post(%{
                 title: "Too many tags",
                 tag_names: "one, two, three, four, five, six"
               })

      assert %{tags: ["must contain at most 5 tags"]} = errors_on(changeset)
    end

    test "list_published_posts/1 filters by category and tag slugs" do
      {:ok, first} =
        Posts.create_post(%{
          title: "OTP article",
          body: "Body",
          summary: "Summary",
          category_name: "Elixir",
          tag_names: "OTP"
        })

      {:ok, first} = Posts.publish_post(first)

      {:ok, second} =
        Posts.create_post(%{
          title: "LiveView article",
          body: "Body",
          summary: "Summary",
          category_name: "Phoenix",
          tag_names: "LiveView"
        })

      {:ok, second} = Posts.publish_post(second)

      assert Enum.map(Posts.list_published_posts(category: "elixir"), & &1.id) == [first.id]
      assert Enum.map(Posts.list_published_posts(tag: "liveview"), & &1.id) == [second.id]
    end

    test "list_related_posts/2 prefers shared tags and excludes the current post" do
      category = category_fixture(%{name: "Architecture"})
      shared_tag = tag_fixture(%{name: "OTP"})
      other_tag = tag_fixture(%{name: "Ecto"})

      current = published_post_with_taxonomy("Current", category, [shared_tag])
      shared = published_post_with_taxonomy("Shared tag", category, [shared_tag])
      same_category = published_post_with_taxonomy("Same category", category, [other_tag])

      assert Enum.map(Posts.list_related_posts(current, 3), & &1.id) == [
               shared.id,
               same_category.id
             ]
    end

    test "increment_views/1 does not lose increments from stale structs" do
      post = post_fixture(%{views: 10})

      assert {:ok, _post} = Posts.increment_views(post)
      assert {:ok, _post} = Posts.increment_views(post)

      assert Posts.get_post!(post.id).views == 12
    end
  end

  defp published_post_with_taxonomy(title, category, tags) do
    post =
      %Alchemistdrops.Posts.Post{}
      |> Alchemistdrops.Posts.Post.publish_changeset(%{
        title: title,
        body: "Body",
        summary: "Summary",
        category_id: category.id
      })
      |> Ecto.Changeset.put_change(
        :published_at,
        DateTime.utc_now() |> DateTime.truncate(:second)
      )
      |> Ecto.Changeset.put_assoc(:tags, tags)
      |> Alchemistdrops.Repo.insert!()

    Alchemistdrops.Repo.preload(post, [:category, :tags, :related_course])
  end
end
