defmodule Alchemistdrops.Markdown do
  @moduledoc """
  Shared Markdown → HTML for blog posts and admin preview.

  Enables GitHub Flavored Markdown extensions (especially **tables**) so pipe tables
  render as `<table>` instead of literal paragraph text.

  Also enables:
  - Heading IDs for anchor navigation (e.g. `## Skills` → `id="skills"`)
  - Mermaid diagram blocks rendered as `<pre class="mermaid">` for client-side rendering
  """

  @extension_opts [
    table: true,
    strikethrough: true,
    autolink: true,
    tasklist: true,
    header_ids: ""
  ]

  @doc """
  Converts Markdown to HTML with GFM extensions and wraps `<table>` in
  `.table-wrapper` for prose styles in `app.css`.

  Heading IDs are generated so anchor links like `[Section](#section)` work.
  Mermaid code blocks are converted to `<pre class="mermaid">` for client-side rendering.

  Always returns `{:ok, html_string}`.
  """
  @spec to_html(String.t()) :: {:ok, String.t()}
  def to_html(content) when is_binary(content) and byte_size(content) > 0 do
    {:ok, doc} = MDEx.parse_document(content, extension: @extension_opts)

    {:ok, html} =
      doc
      |> transform_mermaid()
      |> MDEx.to_html(render: [unsafe: true])

    {:ok, wrap_tables_for_styling(html)}
  end

  def to_html(_), do: {:ok, ""}

  @doc """
  Extracts the rendered level-two and level-three heading outline.

  The returned IDs are the same IDs generated by MDEx for the heading anchors.
  """
  @spec outline(String.t()) :: [%{level: 2 | 3, id: String.t(), label: String.t()}]
  def outline(html) when is_binary(html) do
    ~r/<h([23])>(.*?)<\/h\1>/su
    |> Regex.scan(html, capture: :all_but_first)
    |> Enum.flat_map(fn [level, contents] ->
      case Regex.run(~r/<a\b[^>]*\bid="([^"]+)"[^>]*><\/a>/su, contents, capture: :all_but_first) do
        [id] ->
          label =
            contents
            |> String.replace(~r/<a\b[^>]*><\/a>/su, "")
            |> plain_text()

          [%{level: String.to_integer(level), id: id, label: label}]

        nil ->
          []
      end
    end)
  end

  def outline(_), do: []

  @doc "Returns normalized plain text from a generated HTML fragment."
  @spec plain_text(String.t()) :: String.t()
  def plain_text(html) when is_binary(html) do
    html
    |> String.replace(~r/<[^>]+>/su, " ")
    |> decode_entities()
    |> String.replace(~r/\s+/u, " ")
    |> String.trim()
  end

  def plain_text(_), do: ""

  defp transform_mermaid(document) do
    MDEx.Document.update_nodes(
      document,
      &match?(%MDEx.CodeBlock{info: "mermaid"}, &1),
      &%MDEx.HtmlBlock{literal: "<pre class=\"mermaid\">#{&1.literal}</pre>", nodes: []}
    )
  end

  defp wrap_tables_for_styling(html) when is_binary(html) do
    html
    |> String.replace("<table", "<div class=\"table-wrapper\"><table")
    |> String.replace("</table>", "</table></div>")
  end

  defp decode_entities(value) do
    value
    |> String.replace("&nbsp;", " ")
    |> String.replace("&amp;", "&")
    |> String.replace("&lt;", "<")
    |> String.replace("&gt;", ">")
    |> String.replace("&quot;", "\"")
    |> String.replace("&#39;", "'")
    |> String.replace(~r/&#(\d+);/u, fn entity -> decode_numeric_entity(entity, 10) end)
    |> String.replace(~r/&#x([0-9a-fA-F]+);/u, fn entity -> decode_numeric_entity(entity, 16) end)
  end

  defp decode_numeric_entity(entity, base) do
    digits =
      if base == 16 do
        String.slice(entity, 3, byte_size(entity) - 4)
      else
        String.slice(entity, 2, byte_size(entity) - 3)
      end

    case Integer.parse(digits, base) do
      {codepoint, ""} when codepoint in 0..0x10FFFF -> <<codepoint::utf8>>
      _invalid -> entity
    end
  rescue
    ArgumentError -> entity
  end
end
