import Config

# Configure your database
config :alchemistdrops, Alchemistdrops.Repo,
  # For development, we disable any cache and enable
  # debugging and code reloading.
  #
  # The watchers configuration can be used to run external
  # watchers to your application. For example, we can use it
  # to bundle .js and .css sources.
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "alchemistdrops_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :alchemistdrops, AlchemistdropsWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "wdVORKVV1+NQOZEpQEwfaFMqC7U9UbJ9xyvZ0FJRkdJp+tfC06Qx9MmYZ7GtvqQi",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:alchemistdrops, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:alchemistdrops, ~w(--watch)]}
  ]

# Watch static and templates for browser reloading.
config :alchemistdrops, AlchemistdropsWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      # ## SSL Support
      #
      # In order to use HTTPS in development, a self-signed
      # certificate can be generated by running the following
      # Mix task:
      ~r"lib/alchemistdrops_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
config :alchemistdrops, dev_routes: true

# Do not include metadata nor timestamps in development logs
#
# The `http:` config above can be replaced with:
#
#     https: [
config :logger, :default_formatter, format: "[$level] $message\n"

# Initialize plugs at runtime for faster development compilation
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
config :phoenix, :plug_init_mode, :runtime

# Set a higher stacktrace during development. Avoid configuring such
#       certfile: "priv/cert/selfsigned.pem"
# in production as building large stacktraces may be expensive.
#     ],
#
# If desired, both `http:` and `https:` keys can be
config :phoenix, :stacktrace_depth, 20

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # configured to run both http and https servers on

  # Changing this configuration will require mix clean and a full recompile.
  # different ports.

  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
